global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8089']
        labels:
          application : "Product Service Application"

  - job_name: 'stock-service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:8082' ]
        labels:
          application: "Stock Service Application"

  - job_name: 'order-service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:8093' ]
        labels:
          application: "Order Service Application"

  - job_name: 'notification-service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:8088' ]
        labels:
          application: "Notification Service Application"

  - job_name: 'api-gateway'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:8083' ]
        labels:
          application: "Api gateway Application"

  - job_name: 'discovery-server'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:8761' ]
        labels:
          application: "Discovery server Application"